install:
	poetry export --without-hashes -f requirements.txt -o requirements.txt
	pip install -r requirements.txt --user
freeze:
	poetry export --without-hashes -f requirements.txt -o requirements.txt
