[tool.poetry]
name = "david"
version = "0.1.0"
description = ""
authors = ["IZhao <chzhao8904@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.108.0"
pydantic = "^2.5.3"
SQLAlchemy = "^2.0.25"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
